Databaseremote
rogive/droneservice-backend pull request #1
Opened 2020-08-21 18:46 UTC by rogive

Se crea la base de datos con MongoDB Atlas

![image](https://user-images.githubusercontent.com/66136788/90924084-6a952880-e3b4-11ea-999b-aa3a505f82cb.png)

Se realiza la configuración básica de la conexión a la base de datos en el metodo *list* del controlador pilot.controller.remote que previamente se ha enlazado con la ruta /pilots/listar

![image](https://user-images.githubusercontent.com/66136788/90924163-8f899b80-e3b4-11ea-81f6-bf30c3b77e54.png)

Se incluye en el gitignore el archivo key para el acceso a la base de datos remota.

![image](https://user-images.githubusercontent.com/66136788/90924282-c8c20b80-e3b4-11ea-8665-91eaaa0a61b8.png)

2020-08-21 21:45 UTC, simonhoyos requested changes

2020-08-21 21:45 UTC, simonhoyos commented on src/controllers/pilot.controller.remote.js
> +const { url } = require("../key");
Por qué 2 controladores para pilotos?

2020-08-21 22:55 UTC, rogive commented on src/controllers/pilot.controller.remote.js
> +const { url } = require("../key");
Inicialmente habíamos realizado el controlador del piloto con la base de datos local, y luego se hizo el controlador con la base de datos remoto, pero se me paso eliminar el controlador anterior del piloto. Procedo a eliminar el controlador obsoleto del local

2020-08-22 00:32 UTC, closed without merging

2020-08-22 00:33 UTC, rogive commented
Se realiza cambios en la conexión, se involucra el mongoose, se realizará un nuevo pull request