Demo4
rogive/droneservice-backend pull request #10
Opened 2020-09-22 03:35 UTC by rogive

Se mejoran bugs por typos, se actualizan algunos metodos en controladores, se crea middleware entre otras funciones.
Los siguientes son los cambios realizados:

server.js -> Se actualiza la ruta de pilotos
certificate.controller.js -> Se actualiza  el metodo create para referenciar al piloto
solicitude.controller.js -> se crea el metodo solicitudes para implementar los pagos y guardar al piloto que ya ha comprado el contacto
client.model -> Se ajusta algunos typos
pilot model -> Se añade al modelo los pagos con referencia a las solicitudes
solicitude.model.js -> se añade atributo de telefono dentro de las solicitudes para el manejo de compra de contacto
solicitude.js -> se elimina temporalmente auth en el piloto mientras se arregla el bug al autenticar
middlwares.js -> Se crea un midleware para revisar el estado del pago.

2020-09-22 17:54 UTC, simonhoyos requested changes

2020-09-22 17:54 UTC, simonhoyos commented on src/controllers/pilot.controller.js
> +      console.log(pilot);
borrar console.log

2020-09-22 21:02 UTC, rogive commented on src/controllers/pilot.controller.js
> +      console.log(pilot);
Listo Simón

2020-09-23 15:23 UTC, simonhoyos approved these changes

2020-09-23 15:26 UTC, merged